lanugage: ruby 

rvm: '2.5.0'

addons:
  postgresql: 9.6

env:
  - DB=pgsql


before_script:
  - bundle exec rake db:create

script:
  - bundle exec rake db:migrate RAILS_ENV=test 
  - bundle exec rspec


deploy:

provider: elasticbeanstalk
access_key_id: 
  secure: "XeuJsoe/26NAyNN9oXfbavs5MVlh57tyXmFc+3txFlpADKQZVWwBU4iRLWS9YtnPQcckQzGDi2sHh78CPT2VSXAmXtLSkCiTwu/r3vDwxvsty54PuXgHAnR0vdnOduCK1YsqZwrPR7XNc945pw2fBpCECZjNnSM+rAs+L/q7Ur++DBitKWG1B+0unTSkmCqdhtq21XTxImRLvp2HpjgRBQDcIutEJfb3d4YylJXgk9L2kpBOYdwXxV3CU6ELrLoOfMpthX2JB/hrJL177cVhBjb6aykrjyrNhFvMSCVrjtN0exLlt/hT0AM4mHtdbJ5TKA8ukyogkTuialyNUXWeLCLtXgkaq7zWsAMo/Ayj/XaWJcrrr0o3jBiGu+W9Q85rajhu/8I2M72P2467DtQNjTHvxOvoqjMudLKiD9f0k8o5s/IiTWszDMj6FNWAhYMhl+MAGI6fOqlouX3ZgH5tXMI3i6gRk4pMet86qVihDNUldhLkyWrqYwKpkhjEjzZ3Ljj4b/CMubPeCLyHBlSV9FUM/i3DL1SXwBzH/VCTa5eIER6JGcPaL/xOkf4Cyj3yYfuSaIJo6OmfqBJfSffr2hXX0/KrTxJPh8N/wfhKt0bPnZhFgxYdKykDq9o0TbXDeB+CREDd3s2mnf9j3cdF93VUA4ITJ+GU7ual91HP3Ik="
secret_access_key:
  secure: "pE3Zdva4hFuFhe9RfKdeK0/PHiFxUPxVZ34oQvq9xonlOjB0oaEr1my8fp0Hhfw6EXKht/QjG3pPsBC1E5785jMa3ISxsilraHUq3uuQzz3Th2cZNOM3b2lmn+OIsPr/cIOg/CWrqEkna6wuieHpsi+WgQGfJk9VSdbdH3TUIUOvsB6n3FW/whfiVpIEHvbwC0hLwK0ZxM0HbsG0mL5H6+pT9J/BpepbpwdCWhrVkKx+eN8v2T2DtiOac2GnPeBR2DKWMH/B8222S5175Q2Km0xMBgoZOH2fp/DXWfJ1/Q+659TVXSSWWlohabzzdlpt6xNgQeHOj8sugXm3P1F+FaSGtpx4SpynDTt3gvveTclqR6w5gh44/7drzcNyEtZFqiIvcSYy4uF1HEMMi7ZSutdAwKcilNB92DPVoA0qjXHJH47NU0xqGjYGQpS9rt3hXZdO3az0qqoAAe9xF2yLm9pHLHln8Kcpk7zSvm25x15xDtltOugBFBlym/9dd+dIo6dM14+XXNGqo1z0Ns64jtrkcLbu6IPbBjeCcSB0mB4H7WWvQxksDHlLro6xHLBALAkI+s3sm1xWuXBt5y/76IaOnkx89Nwq7UF/T4DZuZ47kCOU8xDNZK9wWyhtjCOv+eYKCbpeDPuaN0gj9EGMwzDurkmMn/T9DlTdhIyRv7o="
region: "eu-west-2"  
app: "acebook-zukerbros2"
env: "production"
bucket_name: "elasticbeanstalk-eu-west-2-290974039617"
