lanugage: ruby 

rvm: '2.5.0'

addons:
  postgresql: 9.6

env:
  - DB=pgsql


before_script:
  - psql -c 'create database acebook-zuckerbros_test;' -U postgres

script:
  - bundle exec rake db:migrate RAILS_ENV=test 
  - bundle exec rspec